-- supabase/migrations/020_theteller_payment_gateway.sql

-- Extend the existing payment_type check (originally added in migration 008)
-- to allow 'theteller' alongside the existing 'paystack' and 'cod' values.
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_payment_type_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_payment_type_check
  CHECK (payment_type IN ('paystack', 'cod', 'theteller'));

-- TheTeller's own transaction ID (12 digits, generated by us), set at
-- checkout time and matched against on verification — the direct equivalent
-- of the existing paystack_reference column, kept separate since the two
-- providers use different reference formats and different lookup call sites.
ALTER TABLE public.orders ADD COLUMN theteller_transaction_id text;

-- ============================================================
-- PAYMENT GATEWAY SETTINGS (admin-controlled, singleton)
-- ============================================================
CREATE TABLE public.payment_gateway_settings (
  id                boolean PRIMARY KEY DEFAULT true CHECK (id = true),
  paystack_enabled  boolean NOT NULL DEFAULT true,
  theteller_enabled boolean NOT NULL DEFAULT false,
  updated_at        timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.payment_gateway_settings (id) VALUES (true);

ALTER TABLE public.payment_gateway_settings ENABLE ROW LEVEL SECURITY;
-- No public read/write policy — this table is only ever read or written
-- through the admin-client server actions in lib/actions/payment-settings.ts,
-- matching the existing withdrawal_settings table's access pattern exactly
-- (see supabase/migrations/019_seller_withdrawals.sql for that precedent).
